## Consider the below code to answer further questions:

import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Ans :- 

In [1]:
import numpy as np

In [2]:
list_ = ['1', '2', '3', '4', '5']

In [3]:
array_list = np.array(object=list_)

In [4]:
print("Data type of list_:", type(list_))

Data type of list_: <class 'list'>


In [5]:
print("Data type of array_list:", type(array_list))

Data type of array_list: <class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

Ans :- 

In [6]:
import numpy as np

In [7]:
list_ = ['1', '2', '3', '4', '5']

In [8]:
array_list = np.array(object=list_)

In [10]:
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
print("Data types of elements in array_list:")
for item in array_list:
    print(type(item))

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)


* Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [12]:
import numpy as np

In [13]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

In [14]:
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [15]:
print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))


Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

## Q4. Write a code to find the following characteristics of variable, num_array:
* (i) shape
* (ii) size

Ans :- 

In [18]:
import numpy as np

In [19]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

In [20]:
# (i) Shape of the array
shape = num_array.shape

In [21]:
# (ii) Size of the array
size = num_array.size

In [23]:
print("Shape of num_array:", shape)
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

Ans:-

In [26]:
import numpy as np

In [27]:
# Creating a 3x3 array with zeros
zeros_array = np.zeros((3, 3))

In [28]:
print("Array with zeros:")
print(zeros_array)

Array with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Ans :- 

In [29]:
import numpy as np

In [32]:
# Creating a 5x5 identity matrix
identity_matrix = np.eye(5)

In [33]:
print("Identity matrix:")
print(identity_matrix)

Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
